version: "3"
services:
    judge_server:
        image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
        read_only: true
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - /home/gp7/PKUOnlineExamPlatform/backend/problem_data:/test_case
            - /home/gp7/PKUOnlineExamPlatform/Judge-Server/log:/log
            - /home/gp7/PKUOnlineExamPlatform/Judge-Server/run:/judger
        environment:
            - BACKEND_URL=http://0.0.0.0:8080/judge_server_heartbeat
            - SERVICE_URL=http://0.0.0.0:27017
            - TOKEN=JUDGER
        ports:
            - "0.0.0.0:27017:8080"