# Generated by Django 3.2.9 on 2021-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_class_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(choices=[('Student', '学生'), ('Teaching_Assistant', '助教'), ('Teacher', '老师')], max_length=20, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='class_info',
            field=models.IntegerField(blank=True, null=True, verbose_name='班级'),
        ),
    ]
